/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package io.github.synix.helloworld;

public final class R {
  public static final class layout {
    public static final int activity_main=0x7f010000;
  }
  public static final class string {
    public static final int app_name=0x7f020000;
    public static final int hello_msg=0x7f020001;
  }
}